In [7]:

# 1. Create a 1D array of numbers from 0 to 9.

import numpy as np
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [8]:


# 2. Create a 3x3 numpy array of all True's.

import numpy as np
arr = np.full((3, 3), True, dtype=bool)
print(arr)
# OR
arr = np.ones((3, 3), dtype=bool)
print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
 # 3. Extract all odd numbers from an array.

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_arr = arr[arr % 2 == 1]
print(odd_arr)



[1 3 5 7 9]


In [10]:

# 4. Replace all odd numbers in an array with -1.

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)



[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [11]:

# 5. Replace all odd numbers in an array with -1 without changing the original array.

import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_copy = arr.copy()
arr_copy[arr_copy % 2 == 1] = -1
print("Original array:", arr)
print("Modified array:", arr_copy)



Original array: [0 1 2 3 4 5 6 7 8 9]
Modified array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [12]:

# 6. Convert a 1D array to a 2D array with 2 rows.

import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)
# OR
arr_2d = arr.reshape(2, 5)
print(arr_2d)




[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:

# 7. Stack two arrays vertically.

import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
result = np.vstack([arr1, arr2])
print(result)
# OR
result = np.concatenate([arr1, arr2], axis=0)
print(result)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:

# 8. Stack two arrays horizontally.

import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
result = np.hstack([arr1, arr2])
print(result)
# OR
result = np.concatenate([arr1, arr2], axis=1)
print(result)


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [15]:
# 9. Generate a custom sequence in numpy without hardcoding.

import numpy as np
# Generate pattern: 1,1,1,2,2,2,3,3,3,1,1,1,2,2,2,3,3,3
arr = np.repeat([1, 2, 3], 3)
result = np.tile(arr, 2)
print(result)


[1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3]


In [16]:


# 10. Get the common items between two python numpy arrays.

import numpy as np
arr1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common = np.intersect1d(arr1, arr2)
print(common)



[2 4]


In [17]:

# 11. Remove from one array those items that exist in another array.

import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 6, 7, 8, 9])
result = np.setdiff1d(arr1, arr2)
print(result)



[1 2 3 4]


In [18]:

# 12. Get the positions where elements of two arrays match.

import numpy as np
arr1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
positions = np.where(arr1 == arr2)
print(positions)



(array([1, 3, 5, 7]),)


In [19]:

# 13. Extract all numbers between a given range from a numpy array.

import numpy as np
arr = np.array([2, 6, 1, 9, 10, 3, 27])
result = arr[(arr >= 5) & (arr <= 10)]
print(result)



[ 6  9 10]


In [20]:

# 14. Create a function that handles scalars to work on numpy arrays.

import numpy as np

def my_function(a, b):
    return a + b
vectorized_func = np.vectorize(my_function)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
result = vectorized_func(arr1, arr2)
print(result)


[ 6  8 10 12]


In [21]:
# 15. Swap two columns in a 2D numpy array.

import numpy as np
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

arr[:, [0, 1]] = arr[:, [1, 0]]
print("After swapping columns 0 and 1:")
print(arr)



Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After swapping columns 0 and 1:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [22]:
# 16. Swap two rows in a 2D numpy array.

import numpy as np
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

arr[[0, 1], :] = arr[[1, 0], :]
print("After swapping rows 0 and 1:")
print(arr)




Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After swapping rows 0 and 1:
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [23]:
# 17. Reverse the rows of a 2D array.

import numpy as np
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

reversed_arr = arr[::-1]
print("Reversed rows:")
print(reversed_arr)



Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed rows:
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [24]:

# 18. Reverse the columns of a 2D array.

import numpy as np
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

reversed_arr = arr[:, ::-1]
print("Reversed columns:")
print(reversed_arr)



Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed columns:
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [25]:

# 19. Create a 2D array containing random floats between 5 and 10.

import numpy as np
arr = np.random.uniform(5, 10, size=(3, 3))
print(arr)
# OR
arr = np.random.rand(3, 3) * 5 + 5
print(arr)


[[8.90960192 8.54679079 9.93035797]
 [9.1583987  7.29722929 8.8303894 ]
 [7.57920449 8.29023624 7.35877897]]
[[6.91266954 9.82216819 7.22990194]
 [7.88072755 9.40907359 9.69018976]
 [7.70818671 6.38633832 7.47198078]]


In [27]:

# 20. Print only 3 decimal places in a numpy array.

import numpy as np
arr = np.random.random((3, 3))
print("Original array:")
print(arr)

np.set_printoptions(precision=3)
print("Array with 3 decimal places:")
print(arr)


Original array:
[[0.852 0.268 0.172]
 [0.008 0.67  0.745]
 [0.734 0.592 0.095]]
Array with 3 decimal places:
[[0.852 0.268 0.172]
 [0.008 0.67  0.745]
 [0.734 0.592 0.095]]
